version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: currency
    ports:
      - '5432:5432'
    networks:
      - backend
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '8080:80'
    networks:
      - backend
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    networks:
      - backend
    depends_on:
      - postgres
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - '3000:3000'
    networks:
      - backend
    depends_on:
      - api
networks:
  backend:
    driver: bridge
